app/index.js

This adds a pretty simple poor man's `.gitattributes` and `.gitignore` editor. During the configuring phase, sub-generators can call `this.options.addToGitignore()` or `this.options.addToGitattributes()` to append configuration lines to these files.

Allow editing of .git* files

---

src/app/plugins/platform/JavaScript/templates/tsconfig.json

We are still aiming largely for IE11 compat, so we aren't bumping the
target lib version (yet) up to 2015 - just adding collection typings.

Address upstream `@types/react` issue

---

src/app/plugins/platform/Docker/plugins/cms/Drupal8/installDrupal.ts

When the root isn't web/, this directory is superfluous.

Remove web/ directory on D8 install

---

src/app/plugins/platform/JavaScript/index.ts
src/app/plugins/platform/JavaScript/templates/webpack.config.js

This addresses a few issues that have accumulated with the Webpack SPA scaffolding:
* We don't double-invoke `npm install` anymore.
* `CleanWebpackPlugin` 3.0 is now a property of the module, not its sole export. In addition, the options schema changed.
* `css-loader`'s `localIdentName` is now a property of the `modules` object, not a top-level loader option.

Fix webpack scaffold

---

src/app/plugins/platform/Docker/plugins/cms/Drupal8/index.ts

Update linkedDirectories to include the Drupal documentRoot so the generated debloy.rb file adds the correct public files path to Capistrano `linked_dirs`.

[DEVTOOLS-286] Fix Drupal 8 Capistrano deploy

---

.gitignore
src/app/plugins/platform/Docker/plugins/cms/WordPress/index.ts
src/app/plugins/platform/Docker/plugins/cms/WordPress/templates/wp-cli-nostarter.yml.ejs

As discussed in DEVTOOLS-281, WordPress projects that don't use the wp-starter need a wp-cli.yml file showing WP-CLI where the document root is for `f1 wp` commands to work.

Add template for wp-cli.yml file

---

src/app/plugins/platform/Docker/plugins/cms/Drupal8/templates/nginx.conf.ejs

This addresses a bug in the default nginx configuration where enabling the Drupal 8 `redirect` module would trigger an infinite redirect loop.

Fix infinite redirect loops

---

src/app/plugins/platform/Docker/plugins/cms/Drupal8/index.ts

This allows Drush to make full use of available system memory in order to perform intensive tasks.

Remove Drush memory limit

---

src/app/plugins/platform/Docker/plugins/cms/Drupal8/installDrupal.ts
src/app/plugins/platform/Docker/plugins/cms/WordPress/createComposerFile.ts
src/app/plugins/platform/Docker/plugins/cms/WordPress/index.ts

This PR adds [platform information](https://getcomposer.org/doc/06-config.md#platform) to any `composer.json` files emitted by the generator. For WordPress projects, we advertise the `mysql` extension, and for Drupal 8, we expose `gd`, `opcache`, and `pdo`.
For users, this means that `f1 composer install` now works as expected, despite the fact that Composer is run in a container that does not have access to the Drupal/WordPress image's installed extensions.

Expose platform configuration in Composer files

---

src/app/plugins/platform/Docker/plugins/cms/Drupal8/templates/nginx.conf.ejs

This PR increases the size of the FastCGI buffers for Drupal projects in order to account for the sometimes-large cache tag headers that Drupal 8 returns.

Allow large cache tag headers

---

gulpfile.js
src/app/plugins/platform/Docker/dockerfile/Dependency.ts
src/app/plugins/platform/Docker/dockerfile/DockerfileDependencies.ts
src/app/plugins/platform/Docker/dockerfile/computeDependencyBuildCommand.ts
src/app/plugins/platform/Docker/dockerfile/computeDockerfileDependencies.ts
src/app/plugins/platform/Docker/dockerfile/createPHPDockerfile.ts
src/app/plugins/platform/Docker/dockerfile/gd.ts
src/app/plugins/platform/Docker/dockerfile/memcached.ts
src/app/plugins/platform/Docker/dockerfile/opcache.ts
src/app/plugins/platform/Docker/dockerfile/pdo.ts
src/app/plugins/platform/Docker/dockerfile/xdebug.ts
src/app/plugins/platform/Docker/dockerfile/zip.ts
src/app/plugins/platform/Docker/plugins/cms/Drupal8/index.ts
src/app/plugins/platform/Docker/plugins/cms/WordPress/createComposerFile.ts
src/app/plugins/platform/Docker/plugins/cms/WordPress/index.ts

This includes a few fixes found while addressing the WP-CLI SSH functionality:
1. A custom WP-CLI image is now built for WordPress projects.
2. The memory limit in WP-CLI containers is now -1.
3. The memcached extension is installed for WordPress projects when the plugin is enabled.
4. The `createPHPDockerfile()` function has been refactored to use a higher-level abstraction for dependencies.
5. Lint failures are propagated into Gulp build failures.

WP/PHP improvements + refactoring

---

src/app/plugins/Capistrano/templates/capistrano/tasks/wpcli.rake

* Adds a check for WP-CFM being installed, if it is, it will ensure the plugin is activated before attempting to perform a 'config pull'.

WP-CFM Config Pull Enhancement

---

src/app/plugins/Capistrano/templates/capistrano/tasks/wordpress.rb

* Fixes an issue where Composer/dotEnv sites would not deploy correctly due to and attempt to link wp-config to and environment specific config.

Capistrano WordPress Deployment Fix.

---

src/app/plugins/platform/Docker/plugins/cms/Drupal8/index.ts

Updating docker-compose.cli to use working_dir to establish where drush is run from instead of utilizing --root parameter on drush because it overrides aliases attempting to stipulate their own root on remotes.

Update methodology for identifying working directory for drush

---

.eslintrc.js
package-lock.json
package.json
src/app/plugins/platform/Docker/plugins/search/Solr.ts

This removes the option to download config from `search_api_solr`. This hasn't been a supported method for some time, and nodegit has been difficult to install for some users. As a happy side effect, we no longer have any optional dependencies and can enforce stricter rules in ESLint.

Remove solr config download process

---

README.md
src/app/plugins/platform/Docker/plugins/cms/Drupal8/index.ts

Also added a bit of text to the README so I don't have to look up these instructions in the future.

Enabling xdebug pecl extension dependency by default on drupal container.

---

package-lock.json
src/app/plugins/platform/Docker/plugins/cms/WordPress/index.ts

The WordPress version of Gesso won't work without the Timber plugin installed (and enabled). This adds it as part of the install step, similar to the modules Gesso needs on the Drupal side.

Install Timber with Gesso

---

src/app/plugins/platform/Docker/ComposeEditor/index.ts
src/app/plugins/platform/Docker/spawnComposer.ts

This bumps the Composer version used by new projects to 1.9, as required by Drupal 8.8.

Switch to Composer 1.9

---

src/app/plugins/platform/JavaScript/templates/tasks/webpack.js

Was getting errors in this format:
[18:26:02] Using gulpfile ~/Desktop/AFP-GDash-2019/services/wordpress/web/js/chart/gulpfile.js
[18:26:02] Starting 'build'...
Starting type checking service...
[18:26:12] 'build' errored after 9.87 s
[18:26:12] Error: [object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]
[object Object]

Fix eslint error format in gulp webpack task.

---

.buildkite/pipeline.yml
package-lock.json
package.json

This PR works around a newly-discovered issue in TypeScript that causes an out-of-memory issue during the `npm pack` script. I discovered that we didn't catch this on Buildkite because the Docker image was running without the `--unsafe-perm` flag, causing npm to skip the prepack script that invoked Gulp.
I've made a relatively minor bump to TypeScript; we should investigate bumping to the latest version at some later point.

Bump TypeScript version

---

src/app/plugins/platform/Docker/plugins/cms/WordPress/index.ts

This PR defaults WordPress image builds to the `dev` target to align with Drupal.
(Jira: DEVTOOLS-448)

Fix incorrect target for WP images

---

src/app/plugins/platform/Docker/plugins/cms/Drupal8/index.ts
src/app/plugins/platform/Docker/plugins/cms/WordPress/index.ts
src/app/plugins/platform/Docker/xdebug.ts

Adds an env var flag that configures PHP to allow profiling requests.
If the PHP request receives a GET/POST var named "XDEBUG_PROFILE", xdebug will output a cachegrind file to `_profiles` within the Drupal/WP container.
To be configured by https://github.com/forumone/forumone-cli/pull/99

Assist profiling PHP requests

---

src/app/plugins/Capistrano/templates/Gemfile

Update to latest releases for json and i18n Ruby gems to address
security vulnerabilities. Updates beyond v3.4 of Capistrano fail due to
our deployment configuration with the custom rysnc SCM plugin which is
entirely deprecated and unsupported after v3.6.
See https://github.com/capistrano/capistrano/blob/v3.7.0/UPGRADING-3.7.md

Update ruby gem versions for json and i18n gems.

---

src/app/plugins/platform/Docker/xdebug.ts

The test for the Xdebug Profiler feature added as part of
pull request #221 included a typo resulting in a misalignment
with the usage of `f1 up --xdebug-profile` and not triggering
configuration of the profiler as expected.

Align xdebug profiler test variable with f1 cli usage.

---

src/app/plugins/platform/Docker/dockerfile/DockerfileHelper.ts
src/app/plugins/platform/Docker/plugins/cms/Drupal8/createDrupalDockerfile.ts
src/app/plugins/platform/Docker/plugins/cms/WordPress/createWordPressDockerfile.ts

WSGEN-18: Multistage Dockerfile Revisions

---

src/app/plugins/platform/Docker/plugins/search/Elasticsearch.ts

Also corrected case of Elasticsearch.

WSGEN-30: default name & default entry node

---

src/app/plugins/platform/Docker/plugins/cms/Drupal8/installDrupal.ts

Jira Ticket: WSGEN-33
Remove the call to the prepareForPantheon script for new Pantheon Drupal
projects since this should only be run in CI processes preparing to
deploy to the Pantheon repository. If this is run during the install
phase the gitignore file is modified to capture all build assets.

Remove the prepareForPantheon step for new Drupal Pantheon projects.

---

src/app/plugins/platform/Docker/plugins/cms/Drupal8/installDrupal.ts

JIRA Ticket: WSGEN-1
The composer.json file is rewritten during the setup process when
platform dependencies are added. This was resulting in poorly formatted
files since the stringify method wasn't intentionally formatting the
output to the file.
**Note**: This is a replacement for pull request #344 that added unnecessary dependencies.

WSGEN-1: Format composer.json file output when it is rewritten.

---

README.md
package-lock.json
package.json
src/app/plugins/platform/Docker/dockerfile/constants.ts
src/app/plugins/platform/Docker/plugins/cms/Drupal8/index.ts
src/app/plugins/platform/Docker/plugins/cms/Drupal8/installDrupal.ts
src/app/plugins/platform/Docker/plugins/cms/WordPress/createComposerFile.ts
src/app/plugins/platform/Docker/plugins/cms/WordPress/index.ts
src/app/plugins/platform/Docker/spawnComposer.ts

JIRA Ticket: WSGEN-32
The goal of this PR is to implement Composer 2 usage and support into newly generated projects. The generator should also be able to be run on top of existing projects and apply related changes for manual review to update existing projects.
Changes included:
* Added significantly more debug logging and documentation
* Updated Docker images to use the Docker Hub's `composer:2` image
* This deprecates the usage of the `forumone/composer` image
* Apply a `forumone/{project name}` namespace to generated `composer.json` files for WordPress projects
* This is required for Composer 2 support and will need to be manually added to updating projects

WSGEN-32: Composer 2 Support

---

src/app/plugins/platform/Docker/plugins/cms/Drupal8/index.ts
src/app/plugins/platform/Docker/plugins/cms/Drupal8/installDrupal.ts

JIRA Ticket: WSGEN-38
**Note**: This PR is dependent on Composer 2 and is built on top of pull request #345 which should be resolved first.
During the creation of a Drupal project, various composer commands preparing the project were resulting in repetitive install operations that are processor and time-intensive. Upgrading to Composer 2 adds support for a `--no-install` flag on several Composer commands which allows for consolidation of this execution.
Introduced Changes:
• Composer create-project command skips installation of dependencies
* Gesso dependency installation is consolidated to a single Composer command
* Skip installation during the addition of Gesso dependencies
* Execute a final Composer install command once manipulation of the `composer.json` file is completed
* Remove …

WSGEN-38: Consolidate Composer Install Commands During Drupal Setup

---

src/app/plugins/platform/Docker/plugins/cms/Drupal8/index.ts

A simple change, but I'm unaware of any reason _not_ to store the project type selection which allows for re-running the generator consistently.

Store the selected Drupal project target.

---

src/app/plugins/platform/Docker/plugins/cms/Drupal8/index.ts

Since the final installation of Composer dependencies was split to an independent operation in pull request #347, this update enables usage of the `--skip-install` flag to automatically bypass that installation.
**Changed Behavior:** Previously the `--skip-install` flag prevented the question of whether to install Drupal and selection of the project profile altogether, but this behavior may still be accomplished by selecting not to install Drupal at the related prompt.

Add option to skip `composer install` after scaffolding is completed

---

src/buildkite-pipeline/templates/pipeline.yml.ejs

Enable image caching benefits for new commits using caches from the
latest builds for that project by applying a "latest" tag for each
build. Ensuring it is properly namespaced helps to make sure conflicts
across projects don't impact caching benefits.

Fix missing namespacing for "latest" image tags in Buildkite.

---

src/app/index.ts
src/app/plugins/Capistrano/index.ts
src/app/plugins/platform/Docker/index.ts
src/app/plugins/platform/Docker/plugins/cache/Redis.ts
src/app/plugins/platform/Docker/plugins/cms/Drupal8/index.ts
src/app/plugins/platform/Docker/plugins/cms/WordPress/index.ts
src/app/plugins/platform/Docker/plugins/gesso/createGessoGenerator.ts
src/app/plugins/platform/Docker/plugins/search/Elasticsearch.ts
src/app/plugins/platform/Docker/plugins/search/Solr.ts
src/app/plugins/platform/JavaScript/index.ts
src/buildkite-pipeline/index.ts
src/cap-stage/index.ts
src/util.ts

Generators may be executed with the `--uninteractive` flag to
automatically use previously configured answers stored within the
`promptValues` key in `.yo-rc.json`.

Add uninteractive execution support for App and Cap Stage generators.

---

src/app/plugins/platform/Docker/plugins/cms/Drupal8/index.ts
src/app/plugins/platform/Docker/plugins/cms/WordPress/index.ts
test/d8-standard/.yo-rc.json

Replace `public` with `web` as the default web root name for new
projects in order to bring about more consistency with projects hosted
at F1 or Pantheon.

Default new projects being created to use `web` as the web root.
